---
CVP_DEVICES:
  - fqdn: DC1-LEAF1A
    parentContainerName: DC1_LEAF1
    configlets:
      - DC1-AVD_DC1-LEAF1A
  - fqdn: DC1-LEAF1B
    parentContainerName: DC1_LEAF1
    configlets:
      - DC1-AVD_DC1-LEAF1B
  - fqdn: DC1-LEAF2A
    parentContainerName: DC1_LEAF2
    configlets:
      - DC1-AVD_DC1-LEAF2A
  - fqdn: DC1-LEAF2B
    parentContainerName: DC1_LEAF2
    configlets:
      - DC1-AVD_DC1-LEAF2B
CVP_CONTAINERS:
  DC1_FABRIC:
    parentContainerName: Tenant
  DC1_L3LEAFS:
    parentContainerName: DC1_FABRIC
  DC1_LEAF1:
    parentContainerName: DC1_L3LEAFS
  DC1_LEAF2:
    parentContainerName: DC1_L3LEAFS
